Month 7/step 1
WanomiR/react-stellar-burger pull request #1
Opened 2023-11-27 04:13 UTC by WanomiR

Первая часть проекта на проверку.

2023-11-27 05:08 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.

  - App.test.tsx

- Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  ```

  Проверьте во всём проекте.

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-11-27 05:08 UTC, ArslanMustafin commented on src/components/burger-ingridients/burger-ingredients.jsx
> +}
**Надо исправить:**

Вынесите эти компоненты отдельно (создайте папки и файлы). И не забудьте про `prop-types`

2023-11-27 05:08 UTC, ArslanMustafin commented on src/components/burger-ingridients/burger-ingredients.jsx
> +}
**Надо исправить:**

не стоит выносить в отдельный компонент 1 тег.

2023-11-27 05:08 UTC, ArslanMustafin commented on src/components/burger-ingridients/burger-ingredients.jsx
> +                </Cards>
**Можно лучше:**

Здесь и далее.

у каждой категории ингредиентов дублируется верстка, лучше вынести отдельный компонент ingredients-category и переиспользовать его

2023-11-27 05:08 UTC, ArslanMustafin commented on src/components/burger-ingridients/burger-ingredients.jsx
> +                                </React.Fragment>))}
**Надо исправить:**

Здесь и далее.

лучше написать так.

```js
.map(itemData => (
   <Card data={itemData} key={itemData._id} />
 ))
```

2023-11-27 05:08 UTC, ArslanMustafin commented on src/components/burger-ingridients/burger-ingredients.jsx
> +                    {data.filter(item => item.type === "bun")
**Надо исправить:**

Лучше в компоненте делать filter по массиву, а потом отображать полученный массив.

Например:

```js
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);

return (
   ....................
   {buns.map(....................)}
   ..................
)
```

А не располагать фильтрацию в самом jsx

2023-11-27 05:08 UTC, ArslanMustafin commented on src/components/burger-ingridients/burger-ingredients.jsx
> +    data: PropTypes.arrayOf(ingredientPropType),
**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientType.isRequired).isRequired;
```

2023-11-27 05:08 UTC, ArslanMustafin commented on src/components/header/header.jsx
> +}
**Надо исправить:**

Нужно вынести в отдельный компонент (папку, файл). и не забудьте про `prop-types`.
`...props` лучше не использовать.

2023-11-27 05:08 UTC, ArslanMustafin commented on src/utils/prop-types.js
>  });
**Надо исправить:**

Описаны не все поля ингредиента.

2023-11-28 12:42 UTC, WanomiR commented
Арслан, спасибо за ревью. Все удалось поправить за исключением комментария ниже, так как в моей локальной директории такого файла нет.
> Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.
> - App.test.tsx

Отправляю обновленный проект следующим комитом.

2023-11-29 04:17 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличая работа. 🔥

### **Вы молодец! Приступайте к выполнению следующего этапа, не пугайтесь, работа не принята, чтобы была возможность отправить на проверку следующий этап.**

- Все замечания были исправлены;

2023-11-29 04:19 UTC, ArslanMustafin commented
> Арслан, спасибо за ревью. Все удалось поправить за исключением комментария ниже, так как в моей локальной директории такого файла нет.
> 
> > Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.
> > 
> > * App.test.tsx
> 
> Отправляю обновленный проект следующим комитом.

Доброго времени суток. Тут я немного перепутал 😅) так что да, всё что нужно вы исправили 🔥.

2023-12-02 03:26 UTC, closed without merging