Month 7/step 2
WanomiR/react-stellar-burger pull request #2
Opened 2023-12-01 13:35 UTC by WanomiR

Вторая часть проекта на проверку.

2023-12-01 16:20 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Есть модальные окна;
- Данные получают с сервера;

### **Есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/F7gI7lCQ6FjWpw> - тут должен быть немного другой стиль скролла. Сверьтесь ещё раз с дизайном.

- Отметил замечания в коде;

2023-12-01 16:20 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +            const result = await res.json();
**Надо исправить:**

Добавьте проверку ответа сервера - res.ok:

Например:

```js
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответит не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```js
const checkResponse = res => {
  return res.ok ? res.json() : res.json().then(err => Promise.reject(err));
};
```

`fetch(someUrl).then(checkResponse)`

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}
```

и разместить их в отдельном файле `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-12-01 16:20 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +function App({dataUrl}) {
**Надо исправить:**

вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`. Не нужно его использовать в качестве пропса)

2023-12-01 16:20 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +    const [modalState, setModalState] = useState({})
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-12-01 16:20 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +
**Надо исправить:**

для каждого модального окна лучше иметь отдельный стейт и обработчик событий. А также лучше разметить модальные окна в соответствующих компонентах `burger-constructor`, `burger-ingredients` .

2023-12-01 16:20 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +        const canClose = (e.currentTarget.name === "closeButton") || (modalRef.current === e.target) || (e.key === "Escape")
**Надо исправить:**

закрытие попапа по ESC относится к функционалу модального окна и должно быть описано в компоненте Modal, вешайте обработчик при открытии (монтировании) и удаляйте закрытии (размонтировании) применив useEffect

2023-12-01 16:20 UTC, ArslanMustafin commented on src/components/modal-overlay/modal-overlay.jsx
> +rootNode.insertAdjacentHTML("afterend", "<div id='root-modal'></div>")
**Надо исправить:**

У вас ведь есть доступ к `public/index.html`, там и поставьте этот див))

2023-12-01 16:20 UTC, ArslanMustafin commented on src/components/modal-overlay/modal-overlay.jsx
> +const ModalOverlay = forwardRef(({children, handleClose}, ref) => {
**Надо исправить:**

У вас должны быть отдельные компоненты `modal` и `modal-overlay`.


```js
// ModalOverlay
export const ModalOverlay = ({ onClick }) => {
  return <div className={styles.overlay} onClick={onClick} />;
};

ModalOverlay.propTypes = {
  onClick: PropTypes.func,
};

```
Лучше сделать вот такую структура модального окна

```js
// Modal
<>
  <ModalOverlay onClose={handleModalClose} />
  <div className={styles.modal}>...</div>
<>
```

Таким образом вам не нужно использовать рефы и делать какие-то лишние првверки на всплытие.

2023-12-02 07:50 UTC, WanomiR commented
Арслан, спасибо за ревью! 

Все удалось внести, за исключением скролла. Дело в том, что в [UI-библиотеке](https://yandex-practicum.github.io/react-developer-burger-ui-components/docs/) такого елемента нет. Наставник говорит что скролл должен подключаться автоматически (прикладываю скриншот).
<img width="620" alt="Screenshot 2023-12-02 at 10 47 15 AM" src="https://github.com/WanomiR/react-stellar-burger/assets/52817394/3a86b6d0-3b02-4efa-98ff-e018f3b81f0d">
Поэтому я затрудняюсь понять как следует контролировать этот элемент в проекте.

Остальные исправления отправляю следующим комитом.

2023-12-02 11:14 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята удачи в дальнейшем обучении!**

- Все замечания были исправлены;

### **Сделает код лучше:**

Для скролла вам нужно добавить такой код в `app.css`

```css
::-webkit-scrollbar {
width: 8px;
}

::-webkit-scrollbar-track {
background: #2f2f37;
}

::-webkit-scrollbar-thumb {
border: 3px solid #8585ad;
background: #8585ad;
}
```

2023-12-02 11:14 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    ])
**Можно лучше:**

тут лучше использовать PropTypes.node.

2023-12-02 11:14 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +                        }
**Рекомендую исправить:**

Здесь и далее.

Лучше перенести модальное окно и стейт (модального окна) в сам компонент. А не передавать через `children`

2023-12-02 12:46 UTC, merged